otel.instrumentation.common.default-enabled=false
otel.instrumentation.servlet.enabled=true
otel.instrumentation.spring-webmvc.enabled=true
otel.instrumentation.logback-mdc.enabled=true
otel.instrumentation.common.experimental.controller-telemetry.enabled=false
otel.instrumentation.common.experimental.view-telemetry.enabled=false
otel.instrumentation.experimental.span-suppression-strategy=none
otel.propagators=tracecontext,baggage
otel.javaagent.logging=application

